# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: cb451906348f3eba8c822196c3b735a3d938d09b808b6f5ffad1a55e5f6cbd81ea35ea4bbeef885fd89846378ddd2c23320130c2a3ddb0ac8223b85ae4664b47

test:
  secret_key_base: 0f7afa7fe258678558403b0f72735e97c38ae988a1ed1169c054b469538126f041ec9c170ff1d62e90dabbff4ba4c7888056a9889f6ebb906a26ce889dadb0a0

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
